export const CHANGE_INPUT_VALUE = 'CHANGE INPUT VALUE'

export const FETCH_ALBUMS_BY_ARTIST_ID = 'FETCH ALBUMS BY ARTIST ID'
export const FETCH_ALBUMS_BY_ARTIST_ID_FAILED = 'FETCH ALBUMS BY ARTIST ID FAILED'
export const FETCH_ALBUMS_BY_ARTIST_ID_SUCCESSFUL = 'FETCH ALBUMS BY ARTIST ID SUCCESSFUL'

export const FETCH_ALBUM_DETAILS_BY_COLLECTION_ID_REDIRECT = 'FETCH ALBUM DETAILS BY COLLECTION ID REDIRECT'
export const FETCH_ALBUM_DETAILS_BY_COLLECTION_ID_NO_REDIRECT = 'FETCH ALBUM DETAILS BY COLLECTION ID NO REDIRECT'
export const FETCH_ALBUM_DETAILS_BY_COLLECTION_ID_FAILED = 'FETCH ALBUM DETAILS BY COLLECTION ID FAILED'
export const FETCH_ALBUM_DETAILS_BY_COLLECTION_ID_SUCCESSFUL = 'FETCH ALBUM DETAILS BY COLLECTION ID SUCCESSFUL'

export const FETCH_ARTIST_BY_NAME = 'FETCH ARTIST BY NAME'
export const FETCH_ARTIST_BY_NAME_FAILED = 'FETCH ARTIST BY NAME FAILED'
export const FETCH_ARTIST_BY_NAME_SUCCESSFUL = 'FETCH ARTIST BY NAME SUCCESSFUL'