export const SLIDE_BOX = 'SLIDE BOX'
export const STOP_BOX = 'STOP BOX'
export const SPIN_LOGO_CHANGE = 'SPIN LOGO CHANGE'
export const CHANGE_INPUT_VALUE = 'CHANGE INPUT VALUE'



export const FETCH_ALBUMS_BY_ARTIST = 'FETCH ALBUMS BY ARTIST'
export const FETCH_ALBUMS_BY_ARTIST_FAILED = 'FETCH ALBUMS BY ARTIST FAILED'
export const FETCH_ALBUMS_BY_ARTIST_SUCCESSFUL = 'FETCH ALBUMS BY ARTIST SUCCESSFUL'

export const FETCH_ALBUM_DETAILS_BY_UPC = 'FETCH ALBUM DETAILS BY UPC'
export const FETCH_ALBUM_DETAILS_BY_UPC_FAILED = 'FETCH ALBUM DETAILS BY UPC FAILED'
export const FETCH_ALBUM_DETAILS_BY_UPC_SUCCESSFUL = 'FETCH ALBUM DETAILS BY UPC SUCCESSFUL'