export const CHANGE_INPUT_VALUE = 'CHANGE INPUT VALUE'

export const FETCH_ALBUMS_BY_ARTIST = 'FETCH ALBUMS BY ARTIST'
export const FETCH_ALBUMS_BY_ARTIST_FAILED = 'FETCH ALBUMS BY ARTIST FAILED'
export const FETCH_ALBUMS_BY_ARTIST_SUCCESSFUL = 'FETCH ALBUMS BY ARTIST SUCCESSFUL'

export const FETCH_ALBUM_DETAILS_BY_COLLECTION_ID = 'FETCH ALBUM DETAILS BY COLLECTION ID'
export const FETCH_ALBUM_DETAILS_BY_COLLECTION_ID_FAILED = 'FETCH ALBUM DETAILS BY COLLECTION ID FAILED'
export const FETCH_ALBUM_DETAILS_BY_COLLECTION_ID_SUCCESSFUL = 'FETCH ALBUM DETAILS BY COLLECTION ID SUCCESSFUL'